[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

lib_deps =
    https://github.com/atoomnetmarc/TFT_eSPI-ST7789-76x284.git

build_flags =
  -Os
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DUSER_SETUP_LOADED=1

  ; Display
  -DST7789_DRIVER=1
  -DTFT_WIDTH=76
  -DTFT_HEIGHT=284

  ; Physically proven ESP32-S3 wiring
  -DTFT_MISO=-1
  -DTFT_MOSI=11
  -DTFT_SCLK=12
  -DTFT_CS=8
  -DTFT_DC=9
  -DTFT_RST=10

  ; Fonts
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DLOAD_GFXFF=1
  -DSMOOTH_FONT=1

  ; Physically proven reference frequency
  -DSPI_FREQUENCY=27000000